# Toml formatting: https://github.com/toml-lang/toml

# Location of scripts (absolute paths ignore this)
# ${Environment} $Variables will be expanded, but not tilde (~).
ScriptPath = "${HOME}/bin/udev.d"

# RULES
# Subsystem is used to filter udev events monitored
# PropName is the name of the device property to match against
# PropValue is the value to match against (suffix match)
# Action the udev "action" to filter on (add, remove, change, online, offline)
# Command is the name of your script/program to run
# Args is a list of arguments to pass to the script/program

# Can watch for external display plug events and run xrandr scripts
[[Rules]]
Subsystem = "drm"
PropName  = "DEVNAME"
PropValue = "/dev/dri/card0"
Action    = "change"
Command   = "set-display"


# Set pulse audio default device to USB Dacs
[[Rules]]
Subsystem = "sound"
PropName  = "ID_MODEL"
PropValue = "Audioengine_D1"
Action    = "change"
Command   = "pactl"
Args      = ["set-default-sink", "Audioengine_D1"]

# Run xinput configuration settings for devices
[[Rules]]
Subsystem = "input"
PropName  = "ID_MODEL"
PropValue = "Kensington_Slimblade_Trackball"
Action    = "add"
Command   = "xinput-slimblade"

