version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: sudo apt-get update
      - run : sudo apt-get install libudev1 libudev-dev
      - run: go test -v
